# Generated by Django 6.1.1 on 2026-09-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='houses/')),
                ('type', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('room_count', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('floor_count', models.IntegerField()),
                ('area', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'db_table': 'houses',
                'ordering': ['-created_at'],
            },
        ),
    ]
