# Generated by Django 6.1.1 on 2026-09-15 14:53

import django.db.models.deletion
from django.db import migrations, models


def migrate_city_names_to_city_model(apps, schema_editor):
    City = apps.get_model('base', 'City')
    House = apps.get_model('base', 'House')
    db_alias = schema_editor.connection.alias
    cities = {}

    houses = House.objects.using(db_alias).all().iterator()
    for house in houses:
        city_name = (house.city or '').strip()
        if not city_name:
            continue

        city = cities.get(city_name)
        if city is None:
            city, _ = City.objects.using(db_alias).get_or_create(name=city_name)
            cities[city_name] = city

        house.city_fk_id = city.pk
        house.save(update_fields=['city_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='city_fk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.city'),
        ),
        migrations.RunPython(migrate_city_names_to_city_model, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='house',
            name='city',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='city_fk',
            new_name='city',
        ),
    ]
