# Generated by Django 6.1.1 on 2026-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_city_alter_house_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cities/'),
        ),
    ]
